### ISSUE TITLE
Alert user of missing dependencies

### ISSUE THREAD

**Issue by brannondorsey** [olab-io/ofSketch#100]
We need some method to alert the user of missing dependencies (Xcode, other libs, etc...) needed to compile projects with ofSketch. Ideally this would be communicated via a pop-up modal to the user informing them of missing dependencies and info links for how to download them.

**Comment by bakercp** [comment]
Or perhaps a command that offers to install it for them?  This needs more research ...

**Comment by bakercp** [comment]
It doesn't look like a command line only install will work on OSX.  The development SDK, etc is included w/ Xcode, and we can't (legally) distribute the required components.  Luckily, it's a 1 button 2 GB install in the app store, which most users should be able to handle.  The goal with ofSketch hasn't been to completely replace native IDEs, but to provide a getting started tool and put working code in front of people before they get discouraged by learning a complex IDE.  

On windows, we can distribute the entire MinGW toolchain (how did windows win this little contest ? :)

On linux, it's just a series of apt-get commands (or similar), which you have to do in order to run open frameworks anyway.

**Comment by brannondorsey** [comment]
This is now being implemented at a most basic level in v0.3.1 by checking if the machine has the `make` program and directing them of install instructions if they do not.

**Comment by brannondorsey** [comment]
Closing. We can open a new issue for:

> Or perhaps a command that offers to install it for them? This needs more research ...
