### ISSUE TITLE
ofSketch Does not compile / run sketches on 10.8.5, Chrome

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#98]
The web interface, etc seemed to work -- but the connection to the server seemed broken ..

@nbriz Could you open up ofSketch and press the "Report Bug" button in the upper right hand corner so we can grab your browser, build information?

When I tested it w/ @nbriz we downloaded 0.3.0 and got the "Running" project message, but didn't actually get a project to run on 10.8.5.

**Comment by brannondorsey** [comment]
From @nbriz on issue https://github.com/olab-io/ofSketch/issues/99#:

like @bakercp said:
The web interface, etc seemed to work -- but the connection to the server seemed broken

### User Info

ofSketch 0.3.0
Target: OSX
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36

**Comment by brannondorsey** [comment]
Just confirmed that it works on an OSX 10.8 machine with the following specs:

#### User Info
- ofSketch 0.3.0
- Target: OSX
- User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11

It seems like this error might only be occurring on 10.8.5. @nbriz, does it work on any browser on your machine?

**Comment by nbriz** [comment]
i'm having same issue on all my other browsers:
safari Version 6.0.5 (8536.30.1)
firefox 31.0

**Comment by bakercp** [comment]
it sounds like there is something wrong with the process launcher ....

---

http://christopherbaker.net

**Comment by brannondorsey** [comment]
@nbriz, do you have Xcode installed? From the terminal, can you navigate to the HelloWorld example project folder in `data/Projects/HelloWorld` and run

```
make && make run
```

**Comment by nbriz** [comment]
![screen shot 2014-08-14 at 5 22 29 pm](https://cloud.githubusercontent.com/assets/2506806/3927876/809ffe76-2401-11e4-848d-fd20ba08dd0a.png)

**Comment by brannondorsey** [comment]
Ah, you are missing some dependencies to actually compile projects from ofSketch. Downloading [Xcode](https://developer.apple.com/xcode/) should install everything you need. I've also opened up an issue (https://github.com/olab-io/ofSketch/issues/100) so that we can better inform users when they are missing this stuff, and provide install instructions.

**Comment by nbriz** [comment]
i've got Xcode Version 4.6.2

question: ur saying that folks will only be able to use ofSketch if they've installed Xcode? maybe this is impossible, but would there be a way to package all those dependencies in ofSketch? i only use Xcode when i absolutely have to ( generally not a fan ) && i've seen students give up on certain projects when simply having to install it ( even that can be more convoluted than in needs to be... but maybe its getting better )

**Comment by brannondorsey** [comment]
I think what you actually need is the Xcode Command Line Tools, which, according to this [article](http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/) can be installed without Xcode. 

Yeah, I don't like the idea of requiring someone to download Xcode in order to use ofSketch. What is the point of a lightweight editor if you have to download a mega 4GB editor just to use it. Its something that we have to think about, but @bakercp actually perhaps knows a bit more about exactly what dependencies we need (although here, the obvious one is `make`).

**Comment by brannondorsey** [comment]
Im not sure about 10.8.5, but with Mavericks the Xcode command line tools should install with this command:

```
xcode-select --install
```

**Comment by nbriz** [comment]
that did it :+1: 

xcode-select --install didn't work for me, but installed command line tools same way i did last time ( through the gui: preferences > downloads > components tab ) ...i've come across this issue b4 ( the case of the Xcode missing command line tools ) 

so there's ur answer :)

**Comment by brannondorsey** [comment]
Ok great! I am going to close this issue then. We need to think hard about ways that we can keep a user's install process brief. We've been relying on Xcode for managing our toolchain with OSX users, although it is true that requiring them to download Xcode can be a large deterrent.

**Comment by bakercp** [comment]
Super!  I think this may actually be possible -- with command line only tools -- which would be super cool!  I'll do a bit more research on this ... when I spin up my new OSX testing images, I'll try out the xcodetools only approach.
